### ISSUE TITLE
How do you path it

### ISSUE THREAD

**Issue by 1qrobo1** [grubbyplaya/Pac-Man-Museum-CE#1]
Title

**Comment by grubbyplaya** [comment]
Path what? Please elaborate.

**Comment by 1qrobo1** [comment]
I meant patch the calculator files

**Comment by 1qrobo1** [comment]
Oops

**Comment by grubbyplaya** [comment]
Use something like [Rom Patcher JS.](https://www.marcrobledo.com/RomPatcher.js/)
PacGG.bps requires Pac-Man for the Game Gear, and PacMSX.bps requires Pac-Man for the MSX.

Rename the patched roms to [PatchName].8xv, and upload those to your 84+ CE.

**Comment by 1qrobo1** [comment]
![image](https://github.com/user-attachments/assets/e063ee8f-232a-41f8-9902-580d749ec3d8)

**Comment by grubbyplaya** [comment]
What are the names of the files you tried to upload?

**Comment by 1qrobo1** [comment]
PAC msx and superpac

**Comment by grubbyplaya** [comment]
What about the extentions?

**Comment by 1qrobo1** [comment]
Pacmsx.bps

**Comment by 1qrobo1** [comment]
Superpac.8xv

**Comment by grubbyplaya** [comment]
you haven't patched PacMSX. Download a ROM of Pac-Man for the MSX and patch the ROM to get the appvar.

**Comment by grubbyplaya** [comment]
v0.5 no longer uses patches in the release, so just upload that release.
